import argparse
import time
from pathlib import Path

import pandas as pd
import requests
from bs4 import BeautifulSoup
from tqdm import tqdm


FOOTER_MARKERS = [
    "theses.fr\nLe moteur de recherche",
    "Le moteur de recherche theses.fr",
    "En savoir plus",
    "Ressources",
    "2026 — theses.fr",
]


def clean_text(text: str) -> str:
    """
    Nettoie un texte extrait du HTML.
    """
    return " ".join(str(text).split()).strip()


def extract_abstract_from_html(html: str) -> str:
    """
    Extrait le résumé depuis le HTML d'une page theses.fr.

    Structure observée :
    Résumé
    FR
    |
    EN
    <texte du résumé>
    theses.fr
    ...

    On extrait donc ce qui se trouve après le bloc Résumé/FR/EN,
    puis on coupe avant le footer.
    """
    soup = BeautifulSoup(html, "lxml")
    text = soup.get_text("\n", strip=True)

    start = text.lower().find("résumé")
    if start == -1:
        return ""

    abstract_block = text[start:]

    prefixes = [
        "Résumé\nFR\n|\nEN\n",
        "Résumé\nFR\n|\nEN",
        "Résumé\nFR",
        "Résumé",
    ]

    for prefix in prefixes:
        if abstract_block.startswith(prefix):
            abstract_block = abstract_block[len(prefix):]
            break

    abstract_block = abstract_block.strip()

    cut_positions = []

    for marker in FOOTER_MARKERS:
        idx = abstract_block.find(marker)
        if idx != -1:
            cut_positions.append(idx)

    if cut_positions:
        abstract_block = abstract_block[: min(cut_positions)]

    return clean_text(abstract_block)


def fetch_abstract(thesis_id: str, timeout: int = 20) -> str:
    """
    Récupère le résumé depuis la page détail d'une thèse.
    """
    url = f"https://theses.fr/{thesis_id}"

    response = requests.get(
        url,
        headers={"User-Agent": "Mozilla/5.0"},
        timeout=timeout,
    )
    response.raise_for_status()

    return extract_abstract_from_html(response.text)


def enrich_abstracts(
    input_path: Path,
    output_path: Path,
    limit: int | None,
    sleep_seconds: float,
) -> pd.DataFrame:
    """
    Enrichit un CSV de thèses avec les résumés extraits depuis theses.fr.

    input_path : CSV brut issu de src.collect.
    output_path : CSV enrichi avec abstracts.
    limit : nombre de lignes à enrichir. Si None, enrichit tout le fichier.
    sleep_seconds : pause entre les requêtes pour éviter de surcharger le site.
    """
    df = pd.read_csv(input_path)

    if "abstract" not in df.columns:
        df["abstract"] = ""

    # Important :
    # Si la colonne abstract est entièrement vide, pandas peut l'interpréter
    # comme float64 à cause des NaN. On force donc un type texte/objet.
    df["abstract"] = df["abstract"].fillna("").astype("object")

    if limit is not None:
        indices = df.head(limit).index
    else:
        indices = df.index

    success_count = 0
    error_count = 0

    for idx in tqdm(indices):
        thesis_id = str(df.at[idx, "id"])

        current_abstract = df.at[idx, "abstract"]
        if pd.notna(current_abstract) and str(current_abstract).strip():
            continue

        try:
            abstract = fetch_abstract(thesis_id)

            if abstract:
                df.at[idx, "abstract"] = abstract
                success_count += 1

        except requests.RequestException as error:
            print(f"Request error for {thesis_id}: {error}")
            error_count += 1

        time.sleep(sleep_seconds)

    output_path.parent.mkdir(parents=True, exist_ok=True)
    df.to_csv(output_path, index=False, encoding="utf-8")

    print(f"Saved enriched dataset to {output_path}")
    print(f"Abstracts extracted: {success_count}")
    print(f"Errors: {error_count}")

    return df


def main() -> None:
    parser = argparse.ArgumentParser()

    parser.add_argument(
        "--input",
        default="data/raw/theses_raw.csv",
        help="Input CSV generated by src.collect.",
    )
    parser.add_argument(
        "--output",
        default="data/raw/theses_raw_enriched.csv",
        help="Output CSV enriched with abstracts.",
    )
    parser.add_argument(
        "--limit",
        type=int,
        default=20,
        help="Number of theses to enrich. Use -1 to enrich all rows.",
    )
    parser.add_argument(
        "--sleep-seconds",
        type=float,
        default=0.3,
        help="Pause between requests.",
    )

    args = parser.parse_args()

    limit = None if args.limit == -1 else args.limit

    enrich_abstracts(
        input_path=Path(args.input),
        output_path=Path(args.output),
        limit=limit,
        sleep_seconds=args.sleep_seconds,
    )


if __name__ == "__main__":
    main()